spring:
  datasource:
    username: turf_store
    password: turf_store
    url: jdbc:mysql://localhost:3306/turf_store
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always